---
abstract: "a simple dispatcher to send logging data to LinkedIn's Kafka"
author:
  - 'Andrew Nelson <anelson@cpan.org>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102341, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Log-Dispatch-Kafka
requires:
  Kafka::Client: 0
  Log::Dispatch::Output: 0
resources:
  repository: https://github.com/holophrastic/log-dispatch-kafka
version: 0.01
